name: Sync Releases

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
    - name: Sync Releases
      uses: repo-sync/github-sync@v2
      with:
        source_repo: Jguer/yay
        source_branch: main
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
